---
- hosts: webserver
  become: yes
  vars:
    build_number: "{{ BUILD_NUMBER }}"
  
  tasks:

    - name: Create deployment directory
      file:
        path: /home/ubuntu/ad
        state: directory
        mode: '0777'

    - name: Download WAR file from JFrog
      ansible.builtin.get_url:
        url: "https://jfroghost123.jfrog.io/ui/repos/tree/General/repo1/CICD/webapp-{{ build_number }}.war"
        dest: /home/ubuntu/ad/webapp.war
        username: vyatishkumar@gmail.com
        password: Doctorstrange@123

    - name: Create backup directory
      file:
        path: /home/ubuntu/backup
        state: directory
        mode: '0777'

    - name: Backup existing WAR file
      copy:
        src: /var/lib/tomcat10/webapps/webapp.war
        dest: /home/ubuntu/backup/webapp.war
        remote_src: yes

    - name: Remove existing WAR file from Tomcat
      file:
        path: /var/lib/tomcat10/webapps/webapp.war
        state: absent

    - name: Deploy new WAR file to Tomcat
      copy:
        src: /home/ubuntu/ad/webapp.war
        dest: /var/lib/tomcat10/webapps/webapp.war
        remote_src: yes
