---
- hosts: websever
  become: yes
  vars:
    build_number: '{{ BUILD_NUMBER }}'
  tasks:
      
    - name: login to jfrog
      shell: docker login -u vyatishkumar@gmail.com -p Doctorstrange@123 jfroghost123.jfrog.io  
    
    - name: pull an image
      shell: docker pull jfroghost123.jfrog.io/dockerrepo/test-managment:{{ BUILD_NUMBER }}
      
    - name: remove container
      shell: docker rm -f devopsAppDeploy
        
    - name: create a application container
      shell: docker run -id --name devopsAppDeploy -p 8111:8080 jfroghost123.jfrog.io/ddeploy/test-managment:{{ BUILD_NUMBER }}
 
   
